name: movio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1+1
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  get_it: ^7.2.0
  get_ip_address: ^0.0.5
  objectbox: ^1.7.2
  objectbox_flutter_libs: ^1.7.2
  objectbox_generator: ^1.7.2
  rive: ^0.10.1
  connectivity_plus: ^3.0.0
  intl: ^0.17.0
  json_serializable: ^6.1.3
  json_annotation: ^4.7.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.12
  uuid: ^3.0.7
  sprintf: ^7.0.0
  timeago: ^3.3.0
  cached_network_image: ^3.2.1
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Open-Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - weight: 300
        - style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
        - weight: 400
        - style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
        - weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
        - weight: 500
        - style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
        - weight: 600
        - style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
        - weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - weight: 700
        - style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - weight: 800
        - style: italic
